// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caption.proto

package com.example.caption.grpc.caption;

public interface CaptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CaptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  string modelName = 2;
   * </pre>
   *
   * <code>string imgPath = 1;</code>
   * @return The imgPath.
   */
  java.lang.String getImgPath();
  /**
   * <pre>
   *  string modelName = 2;
   * </pre>
   *
   * <code>string imgPath = 1;</code>
   * @return The bytes for imgPath.
   */
  com.google.protobuf.ByteString
      getImgPathBytes();
}
