// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caption.proto

package com.example.caption.grpc.caption;

public final class CaptionServiceProto {
  private CaptionServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CaptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CaptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CaptionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CaptionReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcaption.proto\022\004grpc\"!\n\016CaptionRequest\022" +
      "\017\n\007imgPath\030\001 \001(\t\"\037\n\014CaptionReply\022\017\n\007capt" +
      "ion\030\001 \001(\t2J\n\016CaptionService\0228\n\ngetCaptio" +
      "n\022\024.grpc.CaptionRequest\032\022.grpc.CaptionRe" +
      "ply\"\000B9\n com.example.caption.grpc.captio" +
      "nB\023CaptionServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_CaptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_CaptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CaptionRequest_descriptor,
        new java.lang.String[] { "ImgPath", });
    internal_static_grpc_CaptionReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_CaptionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CaptionReply_descriptor,
        new java.lang.String[] { "Caption", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
