// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caption.proto

package com.example.caption.grpc.caption;

public interface CaptionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CaptionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string caption = 1;</code>
   * @return The caption.
   */
  java.lang.String getCaption();
  /**
   * <code>string caption = 1;</code>
   * @return The bytes for caption.
   */
  com.google.protobuf.ByteString
      getCaptionBytes();
}
